In [3]:
import pandas as pd

DataFrame.groupby(by=?)

In [4]:
titanic_df = pd.read_csv("Titanic_data.csv")

In [5]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
Age_mean = titanic_df[["Embarked", "Age","Fare"]].groupby("Embarked")
Age_mean.mean()

                Age       Fare
Embarked
C         30.814769  59.954144
Q         28.089286  13.276030
S         29.445397  27.079812

## Correlation

In [7]:
titanic_df[["Age","Fare"]].corr()

           Age      Fare
Age   1.000000  0.096067
Fare  0.096067  1.000000

In [8]:
titanic_df[["Age","Survived"]].corr()

               Age  Survived
Age       1.000000 -0.077221
Survived -0.077221  1.000000

In [9]:
correlation_matrix = titanic_df[['Age','Fare']].corr()
correlation_matrix

           Age      Fare
Age   1.000000  0.096067
Fare  0.096067  1.000000

In [10]:
Age_survived = titanic_df[["Age","Survived"]].groupby("Age")
Age_survived.mean()

       Survived
Age
0.42        1.0
0.67        1.0
0.75        1.0
0.83        1.0
0.92        1.0
...         ...
70.00       0.0
70.50       0.0
71.00       0.0
74.00       0.0
80.00       1.0

[88 rows x 1 columns]

In [11]:
Age_survived = titanic_df[["Age", "Survived"]].groupby("Age", as_index=False).mean()

print(Age_survived)

      Age  Survived
0    0.42       1.0
1    0.67       1.0
2    0.75       1.0
3    0.83       1.0
4    0.92       1.0
..    ...       ...
83  70.00       0.0
84  70.50       0.0
85  71.00       0.0
86  74.00       0.0
87  80.00       1.0

[88 rows x 2 columns]