In [2]:
import pandas as pd

In [3]:
titanic_df = pd.read_csv("Titanic_data.csv")

In [4]:
titanic_df.shape

(891, 12)

In [5]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
# Dropping column

titanic_df.drop('PassengerId', axis = 1, inplace = True)
titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
# Dropping row

titanic_df(#RowNUmber, )

In [8]:
last_names = [name.split(",")[0] for name in titanic_df.Name]
titanic_df['First Name'] = last_names

In [9]:
first_names = [name.split(",")[1] for name in titanic_df.Name]
titanic_df['First Name'] = first_names

In [10]:
titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First Name
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr. Owen Harris
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs. John Bradley (Florence Briggs Thayer)
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss. Laina
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs. Jacques Heath (Lily May Peel)
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr. William Henry

In [11]:
first_names = [name.split(",")[1][0:5] for name in titanic_df.Name]
first_names

[' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mrs.',
 ' Mrs.',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mast',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Don.',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Mast',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mast',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mast',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Rev.',
 ' Rev.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mast',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mast',
 ' Mast',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mast',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Dr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Rev.',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mrs.',
 ' Miss',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mast',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mast',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Dr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mrs.',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Miss',
 ' Mme.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Dr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Ms. ',
 ' Mr. ',
 ' Mast',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Majo',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Miss',
 ' Majo',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Lady',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Sir.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Rev.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Dr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mlle',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Col.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Dr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Col.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mast',
 ' Mlle',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Capt',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' the ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mrs.',
 ' Dr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mast',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Dr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mrs.',
 ' Mast',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mrs.',
 ' Mr. ',
 ' Jonk',
 ' Mrs.',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mast',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Rev.',
 ' Mrs.',
 ' Mast',
 ' Mr. ',
 ' Miss',
 ' Miss',
 ' Mrs.',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mast',
 ' Mr. ',
 ' Mrs.',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Mrs.',
 ' Mr. ',
 ' Miss',
 ' Mr. ',
 ' Mr. ',
 ' Mrs.',
 ' Rev.',
 ' Miss',
 ' Miss',
 ' Mr. ',
 ' Mr. ']

In [12]:
Salutation = [name.split(",")[1].split(".")[0] for name in titanic_df.Name]
titanic_df['Salutation'] = Salutation

In [13]:
titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First Name,Salutation
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Mr. Owen Harris,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs. John Bradley (Florence Briggs Thayer),Mrs
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss. Laina,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs. Jacques Heath (Lily May Peel),Mrs
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr. William Henry,Mr

In [14]:
# inserting in a row

titanic_df.loc[0,'Cabin'] = 'C23'

In [15]:
titanic_df.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First Name,Salutation
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C23,S,Mr. Owen Harris,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs. John Bradley (Florence Briggs Thayer),Mrs
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Miss. Laina,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Mrs. Jacques Heath (Lily May Peel),Mrs
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Mr. William Henry,Mr

In [16]:
titanic_df.drop(900, inplace = True)

KeyError: '[900] not found in axis'

## Handling NaN or Null value

In [64]:
titanic_df.isna().sum()

Survived        0
Pclass          0
Name            0
Sex             0
Age           177
SibSp           0
Parch           0
Ticket          0
Fare            0
Cabin         686
Embarked        2
First Name      0
Salutation      0
dtype: int64

## imputation

In [66]:
age_mean = titanic_df.Age.mean()
age_mean

np.float64(29.69911764705882)

In [17]:
titanic_df.describe()

         Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200